### ISSUE TITLE
test_vid.mp4

### ISSUE THREAD

**Issue by Hymnhyz** [tancik/StegaStamp#21]
Where is test_vid.mp4？

**Comment by tancik** [comment]
The detector takes a video as one of the arguments. `test_vid.mp4` is an example filename for the video. It should be modified to the name of your captured video.

**Comment by Charmve** [comment]
I also had like to know where should `test_vid.mp4` be put. 

because I met some debug errors, as following.

```
$ python3 detector.py \
  --detector_model detector_models/stegastamp_detector \
  --decoder_model saved_models/stegastamp_pretrained \
  --video test_vid.mp4 \
  --save_video out/test_out
```

![image](https://user-images.githubusercontent.com/29084184/105468664-1258a000-5c4c-11eb-80eb-688e82d0ce2e.png)

![image](https://user-images.githubusercontent.com/29084184/105468825-40d67b00-5c4c-11eb-995b-9cb8585d1a7c.png)

```
test_vid.mp4
Traceback (most recent call last):
  File "detector.py", line 196, in <module>
    main()
  File "detector.py", line 79, in main
    f_height, f_width = frame.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
Thanks. @tancik

**Comment by HanGod1** [comment]
> I also had like to know where should `test_vid.mp4` be put.
> 
> because I met some debug errors, as following.
> 
> ```
> $ python3 detector.py \
>   --detector_model detector_models/stegastamp_detector \
>   --decoder_model saved_models/stegastamp_pretrained \
>   --video test_vid.mp4 \
>   --save_video out/test_out
> ```
> 
> ![image](https://user-images.githubusercontent.com/29084184/105468664-1258a000-5c4c-11eb-80eb-688e82d0ce2e.png)
> 
> ![image](https://user-images.githubusercontent.com/29084184/105468825-40d67b00-5c4c-11eb-995b-9cb8585d1a7c.png)
> 
> ```
> test_vid.mp4
> Traceback (most recent call last):
>   File "detector.py", line 196, in <module>
>     main()
>   File "detector.py", line 79, in main
>     f_height, f_width = frame.shape[0:2]
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```
> 
> Thanks. @tancik



> I also had like to know where should `test_vid.mp4` be put.
> 
> because I met some debug errors, as following.
> 
> ```
> $ python3 detector.py \
>   --detector_model detector_models/stegastamp_detector \
>   --decoder_model saved_models/stegastamp_pretrained \
>   --video test_vid.mp4 \
>   --save_video out/test_out
> ```
> 
> ![image](https://user-images.githubusercontent.com/29084184/105468664-1258a000-5c4c-11eb-80eb-688e82d0ce2e.png)
> 
> ![image](https://user-images.githubusercontent.com/29084184/105468825-40d67b00-5c4c-11eb-995b-9cb8585d1a7c.png)
> 
> ```
> test_vid.mp4
> Traceback (most recent call last):
>   File "detector.py", line 196, in <module>
>     main()
>   File "detector.py", line 79, in main
>     f_height, f_width = frame.shape[0:2]
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```
> 
> Thanks. @tancik

Hello, is your problem solved? Do you know what kind of file should I put in the save_video? Also what kind of video should I take? Could I use camera on the computer screen or printed posters?

**Comment by HanGod1** [comment]
Hello, is your problem solved? Do you know what kind of file should I put in the save_video? Also what kind of video should I take? Could I use camera on the computer screen or printed posters?

**Comment by Charmve** [comment]
```
## 修改前
self.stn_params = Sequential([
            Input(shape=(8, 400, 400, 3)),
            Conv2D(32, (3, 3), strides=2, activation='relu', padding='same'),
            Conv2D(64, (3, 3), strides=2, activation='relu', padding='same'),
            Conv2D(128, (3, 3), strides=2, activation='relu', padding='same'),
            Flatten(),
            Dense(128, activation='relu')
        ])
        
## 修改后
self.stn_params1 = Conv2D(32, (3, 3), strides=2, activation='relu', padding='same')
self.stn_params2 = Conv2D(64, (3, 3), strides=2, activation='relu', padding='same')
self.stn_params3 = Conv2D(128, (3, 3), strides=2, activation='relu', padding='same')
self.stn_params4 = Flatten()
self.stn_params5 = Dense(128, activation='relu')
```
