### ISSUE TITLE
lpips_tf missing?

### ISSUE THREAD

**Issue by yaseryacoob** [tancik/StegaStamp#29]
In trying to train I got this error (tensorflow1.15)

models.py", line 4, in <module>
    import  lpips_tf
ModuleNotFoundError: No module named 'lpips_tf'

Tried to fix with
https://github.com/alexlee-gk/lpips-tensorflow but didn't solve the problem.

What am I missing?

**Comment by yaseryacoob** [comment]
ended up seeing issue #14 and used that update. But now I got an error in the graphy
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    main()
  File "train.py", line 125, in main
    global_step=global_step_tensor)
  File "/vulcanscratch/yaser/NGA/StegaStamp/models.py", line 245, in build_model
    lpips_loss_op = tf.reduce_mean(lpips_tf.lpips(image_input, encoded_image))
  File "/vulcanscratch/yaser/NGA/StegaStamp/lpips/lpips_tf.py", line 83, in lpips
    input_map={input0_name: input0, input1_name: input1})
  File "/vulcanscratch/yaser/NGA/StegaStamp/yyvenvyy3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/vulcanscratch/yaser/NGA/StegaStamp/yyvenvyy3/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/vulcanscratch/yaser/NGA/StegaStamp/yyvenvyy3/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 535, in _import_graph_def_internal
    ', '.join(missing_unused_input_keys))
ValueError: Attempted to map inputs that were not found in graph_def: [0:0, 1:0]

**Comment by yaseryacoob** [comment]
problem solved with re-downloading alexnet.
