### ISSUE TITLE
Error code < TypeError: join() argument must be str or bytes, not 'NoneType' > while training

### ISSUE THREAD

**Issue by ghost** [tancik/StegaStamp#39]
I have cloned the project from github and installed the requirements after than i have specified the "TRAIN_PATH" but when i try to launch the train.py i am facing with error code:

```
Traceback (most recent call last):
  File "C:/Users/yavuz/PycharmProjects/Tensorflowpytorch/StegaStamp/train.py", line 224, in <module>
    main()
  File "C:/Users/yavuz/PycharmProjects/Tensorflowpytorch/StegaStamp/train.py", line 151, in main
    writer = tf.summary.FileWriter(join(LOGS_Path,EXP_NAME),sess.graph)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

Process finished with exit code 1
```

Note:
I have changed the  ///   `parser.add_argument('exp_name', type=str)` /// to  /// `parser.add_argument('--exp_name', type=str) `///
Because i was also having an error in other way.

I have read all the paper and wanted to try it but having hard time on debugging. Because i do not have much experience on python. 

Waiting for your help.

**Comment by tancik** [comment]
I think the exp_name input argument is not being passed in correctly, hence the value is None.

**Comment by ghost** [comment]
I thought as the same way. Any solution suggestion ?

**Comment by Saltyeng** [comment]
I think it was about some incompatibility problem i have solved it but now i am facing with `IndexError: Cannot choose from an empty sequence`

**Comment by Saltyeng** [comment]
I have solved it but now i am facing with error 
```
WARNING:tensorflow:From C:\Users\yavuz\PycharmProjects\Tensorflowpytorch\StegaStamp\models.py:122: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\Users\yavuz\PycharmProjects\Tensorflowpytorch\StegaStamp\models.py:177: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yavuz/PycharmProjects/Tensorflowpytorch/StegaStamp/train.py", line 224, in <module>
    main()
  File "C:/Users/yavuz/PycharmProjects/Tensorflowpytorch/StegaStamp/train.py", line 125, in main
    global_step=global_step_tensor)
  File "C:\Users\yavuz\PycharmProjects\Tensorflowpytorch\StegaStamp\models.py", line 244, in build_model
    lpips_loss_op = tf.reduce_mean(lpips_tf.lpips(image_input, encoded_image))
  File "C:\Users\yavuz\PycharmProjects\Tensorflowpytorch\StegaStamp\lpips\lpips_tf.py", line 73, in lpips
    _download(os.path.join(_URL, pb_fname), cache_dir)
  File "C:\Users\yavuz\PycharmProjects\Tensorflowpytorch\StegaStamp\lpips\lpips_tf.py", line 23, in _download
    filepath, _ = urllib.request.urlretrieve(url, filepath, _progress)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\yavuz\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Process finished with exit code 1
```

Really do not know what to do

**Comment by ghost** [comment]
Solved
